### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by barbosa89** [Jsitech/JShielder#10]
Despues de correr la herrmienta, recibo un mensaje de You don't have permission to access / on this server.

**Comment by Jsitech** [comment]
Como estas intentando acceder al servidor, via la Dirección IP?

**Comment by barbosa89** [comment]
Hola @Jsitech, estoy conectando a través de SSH, me dejó entrar la primera vez, luego ya no, ni siquiera vía navegador, en el navegador se va a ERR_CONNECTION_TIME_OUT, en hosts.deny está agregando muchas IP, el dominio es cotizate.co.

**Comment by Jsitech** [comment]
Con relación al Forbidden es posible que sea ModSecurity haciendo el bloqueo por alguna razon, Accede al archivo /etc/modsecurity/modsecurity.conf y configura SecRuleEngine a DetectionOnly . Por otro lado Jshielder configura el Puerto SSH a 372, Estas intentando acceder por ese puerto? La herramienta configura el servidor con un nivel algo alto de seguridad y cualquier comportamiento anomalo bloquea la IP, es posible que tu IP este bloqueada en Host Deny o haya sido bloqueada por Fail2Ban.. Tienes acceso directo a la consola, no via SSH?

**Comment by Jsitech** [comment]
Por otro Lado, estas usando algún CMS (Wordpress, Drupal, etc)?

**Comment by barbosa89** [comment]
Si, estoy conectando por el puerto 372, tengo acceso via SSH a la consola, ya que es un VPS, estoy usando Laravel... Creí que el problema era PortSentry y lo quité pero continúa... Voy a probar la configuración que me dices...

**Comment by barbosa89** [comment]
Afecta en algo que mi conexión a Internet asigne IPs dinámicas?  Ahora me ha agregado a blacklisted...

**Comment by Jsitech** [comment]
Que tu IP sea dinámica no debe afectarte. Que puede provocar que entres al Blacklist?

*** Que hagas varios intentos de acceder al puerto SSH en un lapso corto de tiempo
* Que intentes crear varias sesiones SSH
* Si intentas acceder desde una PC que no contenga las llaves de Cifrado, Lo va a tomar como autenticación invalida.
* Si has desactivado la llave por alguna razón y estás usando autenticación por password, si entras el password incorrecto cierto número de veces te agregará al Blacklist
* Si Haces algun scan de puertos al servidor**

**Comment by barbosa89** [comment]
Creo que es que he intentado hacer conexión con password...
