### ISSUE TITLE
Update PHP Config

### ISSUE THREAD

**Issue by ghost** [Jsitech/JShielder#16]
https://github.com/Jsitech/JShielder/blob/master/UbuntuServer_18.04LTS/templates/php

I assume this is for configuring the `php.ini` file?

If so, can I add in the latest directives for PHP 7? It adds a few new ones. 

Example:

```
  session.sid_length        = 128
  session.sid_bits_per_character   = 6
```

**Comment by Jsitech** [comment]
> 
> 
> https://github.com/Jsitech/JShielder/blob/master/UbuntuServer_18.04LTS/templates/php
> 
> I assume this is for configuring the `php.ini` file?
> 
> If so, can I add in the latest directives for PHP 7? It adds a few new ones.
> 
> Example:
> 
> ```
>   session.sid_length        = 128
>   session.sid_bits_per_character   = 6
> ```

Yes, the file replaces the current php.ini for a secure one. Go ahead and add the directives.

**Comment by ghost** [comment]
I also need to remove config items no longer in use by PHP since V7.

`safe_mode` is an example of this.

This list shows you all directives ever used by PHP, including ones that have been removed and what version they were removed starting in: http://php.net/manual/en/ini.list.php

**Comment by Jsitech** [comment]
Addressed in Pull request https://github.com/Jsitech/JShielder/commit/14af67e718c8818b0b64383daf6d29a7223d66f7
