### ISSUE TITLE
Can't run Algo

### ISSUE THREAD

**Issue by zoeified** [Jsitech/JShielder#25]
After installing lamp on ubuntu 18.0.4 I get an error message when I try to install Algo.
`./algo: line 22: /home/<user>/algo/env/bin/ansible-playbook: Permission denied
`
Is there anything in the server hardening that would be causing this? That particular line in the ansible-playbook is :
```
line 21: from __future__ import (absolute_import, division, print_function)
line 22: __metaclass__ = type
```

Any ideas?

**Comment by Jsitech** [comment]
Might be the Default Umask set by Jshielder. It sets a umask of 027, so every file created only the owner can read and write and anyone can only read. If the install is trying to modify a file via another user this might be the reason you are getting the Permission denied. Go to the path the installation is trying to access and check the permissions.

**Comment by Jsitech** [comment]
No feedback from user. Closing issue.

**Comment by nabeards** [comment]
I just had this exact same error on CentOS 7. The issue was that the file 
```/home/<user>/algo/.env/bin/ansible-playbook```

was missing the execute bit. Doing
```chmod 775 /home/<user>/algo/.env/bin/ansible-playbook```

resolved the issue for me.
