### ISSUE TITLE
nginx can't install

### ISSUE THREAD

**Issue by DaPoHou** [Jsitech/JShielder#35]
--2019-09-08 04:09:41--  http://nginx.org/download/nginx-1.14.0
Resolving nginx.org (nginx.org)... 95.211.80.227, 62.210.92.35, 2001:1af8:4060:a004:21::e3
Connecting to nginx.org (nginx.org)|95.211.80.227|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-09-08 04:09:42 ERROR 404: Not Found.

--2019-09-08 04:09:42--  http://1.14.0/
Resolving 1.14.0 (1.14.0)... 1.14.0.0
Connecting to 1.14.0 (1.14.0)|1.14.0.0|:80... failed: Connection timed out.
Retrying.

--2019-09-08 04:11:53--  (try: 2)  http://1.14.0/
Connecting to 1.14.0 (1.14.0)|1.14.0.0|:80...

**Comment by Jsitech** [comment]
Just tested the deployment and nginx installed with no issues. I Suggest you check your network configuration.

**Comment by DaPoHou** [comment]
Nginx download address file name is missing suffix .tar.gz

**Comment by Jsitech** [comment]
I cannot replicate the issue, tried 2 deployments and they completed without issues. Cannot tell what exactly is the issue. Are you running this on Ubuntu?

**Comment by DaPoHou** [comment]
Yes! 18.04，Look at the download URL above, missing file format .tar.gz

**Comment by Jsitech** [comment]
I Have run the deployment on several Ubuntu installation and cannot replicate the issue, something must have happen when you clone the repo or some issue with the Ubuntu installation. Did you try to run Jshielder on a fresh Ubuntu Server install?

**Comment by Jsitech** [comment]
Was not able to replicate the issue. No further response from reporting user. Closing.

**Comment by achile81** [comment]
hi,
i have the same issue

.
.
.
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/modsecurity/lib/pkgconfig'
 /usr/bin/install -c -m 644 modsecurity.pc '/usr/local/modsecurity/lib/pkgconfig'
make[2]: Leaving directory '/opt/ModSecurity'
make[1]: Leaving directory '/opt/ModSecurity'
--2020-05-06 23:46:22--  http://nginx.org/download/nginx-1.14.0
Resolving nginx.org (nginx.org)... 95.211.80.227, 62.210.92.35, 2001:1af8:4060:a004:21::e3
Connecting to nginx.org (nginx.org)|95.211.80.227|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-05-06 23:46:23 ERROR 404: Not Found.

--2020-05-06 23:46:23--  http://1.14.0/
Resolving 1.14.0 (1.14.0)... 1.14.0.0
Connecting to 1.14.0 (1.14.0)|1.14.0.0|:80... failed: Connection timed out.
Retrying.

--2020-05-06 23:48:34--  (try: 2)  http://1.14.0/
Connecting to 1.14.0 (1.14.0)|1.14.0.0|:80...
