### ISSUE TITLE
Future updates

### ISSUE THREAD

**Issue by Cooleem** [Jsitech/JShielder#37]
Are you planning to contribute more to this repo? CentOS 7 says it's under development but hasn't had anything added for 2 years. Ubuntu 18.04 LTS hasn't been really touched in 4 months, and I'm questioning if it's still worth using or if there are any security flaws that might've cropped up.

**Comment by Jsitech** [comment]
Still worth using it for the level of security it applies to the server, New features and different OS support will be coming.  The CentOS and Debian build are almost ready, solving a couple of issues.

**Comment by Cooleem** [comment]
Glad to know you're still working on JShielder! I'm considering using it as a personal tool for quickly hardening my servers so I don't need to spend a chunk of time doing it all manually. I currently run Ubuntu 18.04 LTS, but are you planning to work on Ubuntu 19.04 at any point, or do you not track non-LTS releases?

**Comment by yarone-git** [comment]
Jsitech you doing a great job, Looking forward to CentOS 7 repo.

**Comment by Jsitech** [comment]
Current tasks ongoing as of now.
- Finish up Centos Repos
- Test and update for Ubuntu LTS 20.04
- Add Debian Repos
