### ISSUE TITLE
The Customized Run Has Some Errors; Not Running Certain Tasks

### ISSUE THREAD

**Issue by Cooleem** [Jsitech/JShielder#44]
I inquired in a previous issue if JShielder was updated to the new CIS 2.0.1 standard. While testing out all the features with JShielder, I noticed that some of "Customized Run" scripts aren't executing.

Replication:
- Run jshielder.sh as root.
- Enter the "2. Ubuntu Server 18.04 LTS" menu.
- Enter the "6. Customized Run (Only run desired Options)" menu.
- Try running any of the following; they don't execute:
-- 10. Install Nginx with ModSecurity Module and Set OwaspRules
-- 11. Set Nginx Vhost with PHP
-- 12. Set Nginx Vhost
-- 14. Install and Secure PHP for Nginx Server

There are probably more issues, but I've noticed that any scripts related to Nginx don't seem to run. If money is a possible incentive, I'm willing to send money to you via PayPal to get an updated version of JShielder. I love this script; it makes my work securing my servers so much more convenient. CIS also released their benchmark for Ubuntu 20.04 LTS, but I understand if you're not ready to dive into that one just yet. Either way, I hope to hear from you soon. Thank you again for creating this project. I just hope to see an update soon. 🙂

**Comment by Jsitech** [comment]
HI, really apppreciate you creating these issues and letting me know what is not working. Been a little busy with some certifications. I Do have some free time on my hands now, so expect updates soon. Will Prioritize the versions we have and them will take a look at create a script for the newly released LTS.

**Comment by Cooleem** [comment]
> HI, really apppreciate you creating these issues and letting me know what is not working. Been a little busy with some certifications. I Do have some free time on my hands now, so expect updates soon. Will Prioritize the versions we have and them will take a look at create a script for the newly released LTS.

I really appreciate it, thank you. I really love your work, it's helped me through so much headache!

**Comment by Cooleem** [comment]
Also, I forgot to ask, but could you also add two new functions to the hardening process for place /home and /var on separate partitions and setting the permissions? I've been doing it manually since this script doesn't; it only does it for /tmp.
