### ISSUE TITLE
ServerKeyBits

### ISSUE THREAD

**Issue by mehoppe** [Jsitech/JShielder#7]
You may wish to increase the ServerKeyBits in sshd_config-CIS to 1024, from 768.

**Comment by Jsitech** [comment]
The sshd_config will be updated since some options, including ServerkeyBits applies to Protocol version 1. On our Current config we are forcing the use of Protocol 2. New config file for ssh will be available soon.

**Comment by mehoppe** [comment]
Thanks for sharing your work. I just started learning about CIS hardening and have been using this as a resource to learn what bricks my system the best :).
